#!/usr/bin/env python3
"""Generate the references from the library itself.

    python reference.py                    # regenerate docs/iw.md, docs/plot.md, reference-tools.md
    python reference.py --check            # fail if any is out of date (for CI)
    python reference.py --check-examples   # evaluate every example in the notes

Every object in `iw` and `iw.plot`, every attribute on it, and the type and default of each -- read out
of the dataclasses at import time rather than written down beside them.

That is the whole point. A hand-written data dictionary is a promise to update two things whenever you
change one, and it is a promise nobody keeps: the field you added last week is missing, the type you
changed is still the old type, and a reader cannot tell which half is lying. This one cannot drift,
because there is nothing to drift *from* -- it is the source, formatted.

What the source cannot say is what a field is *for*. That lives in the `reference_notes*.py` modules, and
is merged in here so there is one page rather than two -- a structure that cannot fall behind the library, and an
explanation beside every row of it. The merge is checked both ways: a field with no note simply has an
empty cell, and a note naming a field that no longer exists stops the build.
"""

import argparse
import dataclasses
import enum
import inspect
import pathlib
import sys
import types
import typing

ROOT = pathlib.Path(__file__).resolve().parent
DOCS = ROOT / "docs"

sys.path.insert(0, str(ROOT))
from iw import iw as iw_module  # noqa: E402
from iw import plot as plot_module  # noqa: E402
from iw import tools as tools_module  # noqa: E402
import reference_notes  # noqa: E402
import reference_notes_plot  # noqa: E402

BANNER = "*Generated from the source by `reference.py`. Do not edit -- edit the library and re-run.*"


def banner_with_notes(notes) -> str:
    return (f"*Structure generated from the source by `reference.py`; the explanations come from "
            f"`{notes.__name__}.py`. Do not edit this file -- edit those and re-run.*")


PAGES = [
    {
        "path": DOCS / "iw.md",
        "module": iw_module,
        "notes": reference_notes,
        "title": reference_notes.TITLE,
        "intro": reference_notes.INTRO,
    },
    {
        "path": DOCS / "plot.md",
        "module": plot_module,
        "notes": reference_notes_plot,
        "title": reference_notes_plot.TITLE,
        "intro": reference_notes_plot.INTRO,
    },
    {
        "path": DOCS / "reference-tools.md",
        "module": tools_module,
        "title": "`iw.tools` — helpers",
        "intro": (
            "The convenience constructors for the two trigger payloads that are a trap to write by "
            "hand. **Nothing here is part of the world format** — that is what `iw` mirrors, one field "
            "for one field. These take a tracked item and build the redundant condition or effect the "
            "engine wants, writing the item's id once instead of the two places that must agree.\n"
            "\n"
            "The basic tutorials build triggers from the raw `iw` objects; the advanced tutorials reach "
            "for these once writing them by hand stops scaling."
        ),
    },
]


def type_name(annotation) -> str:
    """A field's type, as you would have written it.

    `iw.py` has `from __future__ import annotations`, so its annotations arrive as strings and we can
    print them straight. `plot.py` does not, so its arrive as objects and we have to put them back
    together. Both are normal; the module decides, not us."""
    if isinstance(annotation, str):
        return annotation
    if annotation is type(None):
        return "None"

    origin = typing.get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))

    args = typing.get_args(annotation)
    if origin in (types.UnionType, typing.Union):
        return " | ".join(type_name(arg) for arg in args)
    name = getattr(origin, "__name__", str(origin))
    return f"{name}[{', '.join(type_name(arg) for arg in args)}]"


def default_of(field: dataclasses.Field) -> str:
    """What you get if you don't set it."""
    if field.default is not dataclasses.MISSING:
        value = field.default
        if isinstance(value, enum.Enum):
            return f"{type(value).__name__}.{value.name}"
        return repr(value)

    if field.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
        factory = field.default_factory  # type: ignore[misc]
        if factory is list:
            return "[]"
        if factory is dict:
            return "{}"
        if dataclasses.is_dataclass(factory):
            return f"{factory.__name__}()"
        # The id fields. Every object gets one automatically, and nothing in this repo ever writes one
        # by hand -- which is the single most important fact about using this library safely.
        return "auto"

    return "required"


def members(module) -> tuple[list, list, list]:
    """What the module defines, in the order it defines it: its dataclasses, its enums, its functions."""
    dataclasses_, enums, functions = [], [], []
    for name, obj in vars(module).items():
        if name.startswith("_") or getattr(obj, "__module__", None) != module.__name__:
            continue
        if dataclasses.is_dataclass(obj):
            dataclasses_.append(obj)
        elif isinstance(obj, type) and issubclass(obj, enum.Enum):
            enums.append(obj)
        elif inspect.isfunction(obj):
            functions.append(obj)
    return dataclasses_, enums, functions


def docstring(obj) -> str:
    """An object's *own* docstring, as one paragraph, or nothing.

    Two things that look like docstrings and are not. A dataclass with none is given one by `@dataclass`
    -- its constructor signature, which is what the block below already says, only harder to read. And a
    class with none inherits its parent's, so every one of our enums would come out documented as "Enum
    where members are also (and must be) strings", which is true of `StrEnum` and tells a reader nothing
    about ours. Only what was written here counts.

    Kept to one paragraph on purpose: this is an index, and an index that quotes three at you is worse."""
    own = obj.__dict__.get("__doc__") if isinstance(obj, type) else obj.__doc__
    if not own or own.startswith(f"{getattr(obj, '__name__', '')}("):
        return ""
    first = inspect.cleandoc(own).split("\n\n")[0]
    return " ".join(line.strip() for line in first.splitlines())


def unquote(annotation: str) -> str:
    """`from __future__ import annotations` hands us the source text of an annotation -- and when that
    source was itself a string (`item: "TrackedItem | str"`, the forward reference), the quotes come
    along with it. They are not part of the type."""
    return annotation.strip("\"'")


def signature(function) -> str:
    """A function as you would call it. `inspect.signature` renders string annotations with their quotes
    still on and enum defaults as `<TrackedItemAction.SET: 'set'>`, neither of which is what you type."""
    sig = inspect.signature(function)
    params = []
    for name, parameter in sig.parameters.items():
        rendered = name
        if parameter.annotation is not inspect.Parameter.empty:
            rendered += f": {unquote(type_name(parameter.annotation))}"
        if parameter.default is not inspect.Parameter.empty:
            default = parameter.default
            if isinstance(default, enum.Enum):
                rendered += f" = {type(default).__name__}.{default.name}"
            else:
                rendered += f" = {default!r}"
        params.append(rendered)

    returns = ""
    if sig.return_annotation is not inspect.Signature.empty:
        returns = f" -> {unquote(type_name(sig.return_annotation))}"
    return f"{function.__name__}({', '.join(params)}){returns}"


def cell(text: str) -> str:
    """Text safe to put in a Markdown table cell. A pipe in a cell is a column break, and types like
    `str | None` are full of them."""
    return text.replace("|", "\\|")


def render_dataclass(cls, notes=None) -> list[str]:
    """One object: what it is, then a row per attribute -- type, default, and what it is for."""
    field_notes = (notes.FIELDS.get(cls.__name__, {}) if notes else {})
    parts = [f"### `{cls.__name__}`", ""]
    if summary := docstring(cls):
        parts += [summary, ""]

    header = "| attribute | type | default | what it's for |" if notes else "| attribute | type | default |"
    parts += [header, "|---|---|---|---|" if notes else "|---|---|---|"]
    for f in dataclasses.fields(cls):
        row = f"| `{f.name}` | `{cell(type_name(f.type))}` | `{cell(default_of(f))}` |"
        if notes:
            row += f" {field_notes.get(f.name, '')} |"
        parts.append(row)
    parts.append("")

    if notes and (note := notes.CLASS_NOTES.get(cls.__name__)):
        parts += [note, ""]
    return parts


def render_enum(cls, notes=None) -> list[str]:
    """One enum: every member, the string the engine reads, and -- where the notes supply them -- what
    the member does and a line of code using it."""
    members_notes = (notes.ENUMS.get(cls.__name__, {}) if notes else {})
    parts = [f"### `{cls.__name__}`", ""]
    if summary := docstring(cls):
        parts += [summary, ""]

    if members_notes:
        parts += ["| member | value in the JSON | what it does | example |", "|---|---|---|---|"]
        for member in cls:
            what, example = members_notes.get(member.name, ("", ""))
            parts.append(f"| `{member.name}` | `{member.value}` | {what} | `{cell(example)}` |")
    else:
        parts += ["| member | value in the JSON |", "|---|---|"]
        parts += [f"| `{member.name}` | `{member.value}` |" for member in cls]
    parts.append("")

    if notes and (note := notes.ENUM_NOTES.get(cls.__name__)):
        parts += [note, ""]
    return parts


def render_function(function, notes=None) -> list[str]:
    parts = [f"### `{signature(function)}`", ""]
    if summary := docstring(function):
        parts += [summary, ""]
    function_notes = getattr(notes, "FUNCTION_NOTES", {}) if notes else {}
    if note := function_notes.get(function.__name__):
        parts += [note, ""]
    return parts


def check_notes(module, notes) -> list[str]:
    """Every note must still describe something real. A note for a field that has been renamed or deleted
    is worse than no note: it reads as current, and there is nothing to make it stop."""
    dataclasses_, enums, functions = members(module)
    by_name = {cls.__name__: cls for cls in dataclasses_}
    enums_by_name = {cls.__name__: cls for cls in enums}
    problems = []

    for cls_name, fields_ in notes.FIELDS.items():
        cls = by_name.get(cls_name)
        if cls is None:
            problems.append(f"FIELDS has notes for {cls_name!r}, which is not a dataclass in the module")
            continue
        real = {f.name for f in dataclasses.fields(cls)}
        for extra in sorted(set(fields_) - real):
            problems.append(f"FIELDS[{cls_name!r}] describes {extra!r}, which is not a field")

    for cls_name in notes.CLASS_NOTES:
        if cls_name not in by_name:
            problems.append(f"CLASS_NOTES has a note for {cls_name!r}, which is not a dataclass")

    for enum_name, member_notes in notes.ENUMS.items():
        cls = enums_by_name.get(enum_name)
        if cls is None:
            problems.append(f"ENUMS has notes for {enum_name!r}, which is not an enum in the module")
            continue
        real = {member.name for member in cls}
        for extra in sorted(set(member_notes) - real):
            problems.append(f"ENUMS[{enum_name!r}] describes {extra!r}, which is not a member")

    for enum_name in notes.ENUM_NOTES:
        if enum_name not in enums_by_name:
            problems.append(f"ENUM_NOTES has a note for {enum_name!r}, which is not an enum")

    function_names = {function.__name__ for function in functions}
    for name in getattr(notes, "FUNCTION_NOTES", {}):
        if name not in function_names:
            problems.append(f"FUNCTION_NOTES has a note for {name!r}, which is not a function")

    return problems


def to_markdown(page: dict) -> str:
    notes = page.get("notes")
    dataclasses_, enums, functions = members(page["module"])
    parts = [f"# {page['title']}", "", banner_with_notes(notes) if notes else BANNER, "", page["intro"], ""]

    parts += ["## The objects", ""]
    for cls in dataclasses_:
        parts += render_dataclass(cls, notes)

    if enums:
        parts += ["## The enums", "",
                  "Every one is a `StrEnum`, so a member *is* the string the engine reads — you can pass "
                  "the member or its value and the JSON comes out the same. Prefer the member: a typo in "
                  "a member name is an `AttributeError`, and a typo in a string is a world that loads "
                  "and quietly does nothing.", ""]
        if notes:
            parts += ["The examples below all run, and refer to these:", "",
                      "```python", notes.EXAMPLE_SETUP, "```", ""]
        for cls in enums:
            parts += render_enum(cls, notes)

    if functions:
        parts += ["## The functions", ""]
        for function in functions:
            parts += render_function(function, notes)

    for heading, body in (notes.TAIL_SECTIONS if notes else []):
        parts += [f"## {heading}", "", body, ""]

    return "\n".join(parts).rstrip() + "\n"


def check_examples(notes) -> list[str]:
    """Evaluate every example in the notes. An example that does not run is a lie told in code, and it is
    the kind a reader trusts hardest."""
    import iw
    from iw.tools import set_tracked_item, tracked_item_is

    iw.reset_ids()
    context = {"iw": iw, "set_tracked_item": set_tracked_item, "tracked_item_is": tracked_item_is}
    exec(notes.EXAMPLE_SETUP, context)

    problems = []
    for enum_name, member_notes in notes.ENUMS.items():
        for member_name, (_, example) in member_notes.items():
            if not example:
                continue
            try:
                eval(example, context)
            except Exception as error:
                problems.append(f"{enum_name}.{member_name}: {type(error).__name__}: {error}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if a page is out of date")
    parser.add_argument("--check-examples", action="store_true", help="evaluate every example in the notes")
    args = parser.parse_args()

    if args.check_examples:
        problems = []
        for page in PAGES:
            if notes := page.get("notes"):
                problems += check_examples(notes)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(f"  {'FAILED' if problems else 'every example runs'}")
        return 1 if problems else 0

    for page in PAGES:
        if not (notes := page.get("notes")):
            continue
        if problems := check_notes(page["module"], notes):
            print(f"{notes.__name__}.py describes things that no longer exist:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            return 1

    stale = []
    for page in PAGES:
        content = to_markdown(page)
        destination = page["path"]
        current = destination.read_text() if destination.exists() else None
        if args.check:
            if current != content:
                stale.append(destination.relative_to(ROOT))
            continue
        destination.write_text(content)
        print(f"  {destination.relative_to(ROOT)}{'' if current == content else '  (updated)'}")

    if stale:
        print("Out of date -- run `python reference.py`:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    if args.check:
        print("  data dictionaries are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
