"""The jump links: which systems connect to which, and how hard the jump is.

The *edges* of the star map. A `JumpLink` is a plain fact -- two systems, a difficulty, a travel time --
the same kind of inert data as a `System`, and it lives here beside the nodes so the whole of the map's
data is in one subsystem. What you *do* with the graph -- pathfinding, the routes out to each gateway, the
triggers that move you across it -- is logic, and lives in `navigation.py`.

The links are grouped by the cluster of their first system, purely so the table reads; the order within
and between groups is otherwise arbitrary (cross-cluster links sit under their first endpoint's cluster).
"""
from __future__ import annotations

from ..enums import JumpDifficulty
from . import antares, canopus, hyades, inner_systems, pleiades, polaris
from .models import JumpLink


ALL_JUMP_LINKS: list[JumpLink] = [
    # ---- Inner Systems ----
    JumpLink(JumpDifficulty.Soft, inner_systems.ALDEBARAN, inner_systems.HAMAL),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALDEBARAN, hyades.AIN),
    JumpLink(JumpDifficulty.Moderate, inner_systems.ALDEBARAN, inner_systems.KALINAN),
    JumpLink(JumpDifficulty.Hard, inner_systems.ALDEBARAN, inner_systems.SHERATAN),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALDERAMIN, inner_systems.RUCHBAH),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALGOL, inner_systems.RUCHBAH),
    JumpLink(JumpDifficulty.Hard, inner_systems.ALGOL, inner_systems.VEGA),
    JumpLink(JumpDifficulty.Soft, inner_systems.BARGHAL, inner_systems.DENEBOLA),
    JumpLink(JumpDifficulty.Hard, inner_systems.BARGHAL, inner_systems.GADDACK),
    JumpLink(JumpDifficulty.Moderate, inner_systems.BARGHAL, inner_systems.REGULUS),
    JumpLink(JumpDifficulty.Soft, inner_systems.ANGIRAS, inner_systems.HERAK),
    JumpLink(JumpDifficulty.Moderate, inner_systems.ALPHA_CENTAURI, inner_systems.ARCTURUS),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALPHA_CENTAURI, inner_systems.RASALHAGUE),
    JumpLink(JumpDifficulty.Hard, inner_systems.ALPHA_CENTAURI, inner_systems.SABIX),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALPHA_CENTAURI, inner_systems.SOL),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALPHA_CENTAURI, inner_systems.TAU_CETI),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALPHECCA, inner_systems.ARCTURUS),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALPHECCA, inner_systems.PHEDA),
    JumpLink(JumpDifficulty.Moderate, inner_systems.ALTAIR, inner_systems.DENEBOLA),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALTAIR, inner_systems.SIRIUS),
    JumpLink(JumpDifficulty.Soft, inner_systems.ALTAIR, inner_systems.VEGA),
    JumpLink(JumpDifficulty.Soft, inner_systems.ARCTURUS, inner_systems.EPSILON_ERIDANI),
    JumpLink(JumpDifficulty.Moderate, inner_systems.HERAK, inner_systems.RASALHAGUE),
    JumpLink(JumpDifficulty.Moderate, inner_systems.ARCTURUS, inner_systems.MIZAR),
    JumpLink(JumpDifficulty.Soft, inner_systems.ARCTURUS, polaris.POLARIS),
    JumpLink(JumpDifficulty.Hard, inner_systems.ARCTURUS, inner_systems.NUKALI),
    JumpLink(JumpDifficulty.Soft, inner_systems.CAPELLA, inner_systems.MEGREZ),
    JumpLink(JumpDifficulty.Soft, inner_systems.CAPELLA, inner_systems.KALINAN),
    JumpLink(JumpDifficulty.Soft, inner_systems.CAPELLA, inner_systems.SHERATAN),
    JumpLink(JumpDifficulty.Soft, inner_systems.CAPELLA, inner_systems.TAU_CETI),
    JumpLink(JumpDifficulty.Moderate, inner_systems.CAPH, inner_systems.RASALHAGUE),
    JumpLink(JumpDifficulty.Moderate, inner_systems.CAPH, inner_systems.RUCHBAH),
    JumpLink(JumpDifficulty.Hard, inner_systems.CAPH, inner_systems.SOL),
    JumpLink(JumpDifficulty.Soft, inner_systems.CASTOR, inner_systems.FOMALHAUT),
    JumpLink(JumpDifficulty.Moderate, inner_systems.CASTOR, inner_systems.GADDACK),
    JumpLink(JumpDifficulty.Soft, inner_systems.CASTOR, inner_systems.POLLUX),
    JumpLink(JumpDifficulty.Hard, inner_systems.CASTOR, inner_systems.TAU_CETI),
    JumpLink(JumpDifficulty.Moderate, inner_systems.DENEBOLA, inner_systems.REGULUS),
    JumpLink(JumpDifficulty.Soft, inner_systems.DENEBOLA, inner_systems.SIRIUS),
    JumpLink(JumpDifficulty.Moderate, inner_systems.EPSILON_ERIDANI, inner_systems.MIZAR),
    JumpLink(JumpDifficulty.Soft, inner_systems.EPSILON_ERIDANI, inner_systems.TAU_CETI),
    JumpLink(JumpDifficulty.Soft, inner_systems.CAPH, inner_systems.PROCYON),
    JumpLink(JumpDifficulty.Moderate, inner_systems.FOMALHAUT, inner_systems.SOL),
    JumpLink(JumpDifficulty.Soft, inner_systems.FOMALHAUT, inner_systems.ZOSMA),
    JumpLink(JumpDifficulty.Soft, inner_systems.GADDACK, inner_systems.POLLUX),
    JumpLink(JumpDifficulty.Moderate, inner_systems.GADDACK, inner_systems.REGULUS),
    JumpLink(JumpDifficulty.Soft, inner_systems.HAMAL, inner_systems.KALINAN),
    JumpLink(JumpDifficulty.Moderate, inner_systems.KALINAN, inner_systems.SHERATAN),
    JumpLink(JumpDifficulty.Hard, inner_systems.HERAK, inner_systems.PHEDA),
    JumpLink(JumpDifficulty.Moderate, inner_systems.PHEDA, inner_systems.NUKALI),
    JumpLink(JumpDifficulty.Soft, inner_systems.POLLUX, inner_systems.PROCYON),
    JumpLink(JumpDifficulty.Soft, inner_systems.POLLUX, inner_systems.SHERATAN),
    JumpLink(JumpDifficulty.Soft, inner_systems.CAPH, inner_systems.PROCYON),
    JumpLink(JumpDifficulty.Moderate, inner_systems.RASALHAGUE, inner_systems.SABIX),
    JumpLink(JumpDifficulty.Hard, inner_systems.RASALHAGUE, inner_systems.VEGA),
    JumpLink(JumpDifficulty.Soft, inner_systems.REGULUS, inner_systems.ZOSMA),
    JumpLink(JumpDifficulty.Soft, inner_systems.SABIX, inner_systems.GENUBI),
    JumpLink(JumpDifficulty.Soft, inner_systems.SIRIUS, inner_systems.SOL),
    JumpLink(JumpDifficulty.Soft, inner_systems.SOL, inner_systems.TAU_CETI),

    # ---- Antares ----
    JumpLink(JumpDifficulty.Moderate, antares.ATR_6619, antares.ACRAB),
    JumpLink(JumpDifficulty.Hard, antares.ATR_6619, antares.LESATH),
    JumpLink(JumpDifficulty.Soft, antares.ACRAB, antares.DSCHUBBA),
    JumpLink(JumpDifficulty.Moderate, antares.ACRAB, antares.SARGAS),
    JumpLink(JumpDifficulty.Soft, antares.ACRAB, antares.SHAULA),
    JumpLink(JumpDifficulty.Soft, antares.ACRAB, antares.YED_PRIOR),
    JumpLink(JumpDifficulty.Soft, antares.ANTARES, inner_systems.CAPELLA),
    JumpLink(JumpDifficulty.Soft, antares.ANTARES, antares.DSCHUBBA),
    JumpLink(JumpDifficulty.Hard, antares.ANTARES, antares.KAUS),
    JumpLink(JumpDifficulty.Moderate, antares.ANTARES, inner_systems.SABIX),
    JumpLink(JumpDifficulty.Moderate, antares.DSCHUBBA, antares.KORNEPHOROS),
    JumpLink(JumpDifficulty.Hard, antares.DSCHUBBA, antares.ATR_4401),
    JumpLink(JumpDifficulty.Soft, antares.DSCHUBBA, antares.DIZUO),
    JumpLink(JumpDifficulty.Moderate, antares.DSCHUBBA, antares.SHAULA),
    JumpLink(JumpDifficulty.Hard, antares.ATR_0088, antares.ATR_8812),
    JumpLink(JumpDifficulty.Hard, antares.ATR_0088, antares.SARGAS),
    JumpLink(JumpDifficulty.Moderate, antares.ATR_8812, antares.NUNKI),
    JumpLink(JumpDifficulty.Soft, antares.KAUS, antares.NUNKI),
    JumpLink(JumpDifficulty.Soft, antares.KAUS, antares.ATR_1156),
    JumpLink(JumpDifficulty.Soft, antares.KAUS, antares.SADAL),
    JumpLink(JumpDifficulty.Moderate, antares.LESATH, antares.SHAULA),
    JumpLink(JumpDifficulty.Soft, antares.NUNKI, antares.SARGAS),
    JumpLink(JumpDifficulty.Moderate, antares.NUNKI, antares.SHAULA),
    JumpLink(JumpDifficulty.Soft, antares.NUNKI, antares.SULAFAT),
    JumpLink(JumpDifficulty.Hard, antares.DIZUO, antares.YED_PRIOR),
    JumpLink(JumpDifficulty.Hard, antares.ATR_1156, antares.SULAFAT),
    JumpLink(JumpDifficulty.Soft, antares.SARGAS, antares.SHAULA),

    # ---- Canopus ----
    JumpLink(JumpDifficulty.Moderate, canopus.ACRUX, canopus.ASPID),
    JumpLink(JumpDifficulty.Soft, canopus.ACRUX, canopus.MIRZAM),
    JumpLink(JumpDifficulty.Soft, canopus.ACRUX, canopus.NAOS),
    JumpLink(JumpDifficulty.Hard, canopus.ACRUX, canopus.CNP_2190),
    JumpLink(JumpDifficulty.Soft, canopus.ADHARA, canopus.CANOPUS),
    JumpLink(JumpDifficulty.Moderate, canopus.ADHARA, canopus.PLACIDUS),
    JumpLink(JumpDifficulty.Soft, canopus.ADHARA, canopus.MIRZAM),
    JumpLink(JumpDifficulty.Soft, canopus.ADHARA, canopus.PHAET),
    JumpLink(JumpDifficulty.Soft, canopus.ALSEPHINA, canopus.PLACIDUS),
    JumpLink(JumpDifficulty.Moderate, canopus.ALSEPHINA, canopus.PHAET),
    JumpLink(JumpDifficulty.Moderate, canopus.ASPID, canopus.AVIOR),
    JumpLink(JumpDifficulty.Soft, canopus.ASPID, canopus.CNP_3318),
    JumpLink(JumpDifficulty.Soft, canopus.ASPID, canopus.SUHAIL),
    JumpLink(JumpDifficulty.Soft, canopus.AVIOR, canopus.PLACIDUS),
    JumpLink(JumpDifficulty.Moderate, canopus.AVIOR, canopus.MIRZAM),
    JumpLink(JumpDifficulty.Soft, canopus.AVIOR, canopus.TURAIS),
    JumpLink(JumpDifficulty.Hard, canopus.CNP_3318, canopus.NIHAL),
    JumpLink(JumpDifficulty.Soft, canopus.CANOPUS, inner_systems.CASTOR),
    JumpLink(JumpDifficulty.Soft, canopus.ADHARA, canopus.CNP_0871),
    JumpLink(JumpDifficulty.Moderate, canopus.MIRZAM, canopus.PLACIDUS),
    JumpLink(JumpDifficulty.Hard, canopus.CANOPUS, canopus.NAOS),
    JumpLink(JumpDifficulty.Moderate, canopus.CANOPUS, inner_systems.POLLUX),
    JumpLink(JumpDifficulty.Moderate, canopus.CANOPUS, canopus.SUHAIL),
    JumpLink(JumpDifficulty.Moderate, canopus.CNP_0871, canopus.CNP_5502),
    JumpLink(JumpDifficulty.Hard, canopus.CNP_0871, canopus.PHAET),
    JumpLink(JumpDifficulty.Hard, canopus.NAOS, canopus.SUHAIL),
    JumpLink(JumpDifficulty.Moderate, canopus.NIHAL, canopus.TURAIS),

    # ---- Hyades ----
    JumpLink(JumpDifficulty.Soft, hyades.SECUNDA_HYADUM, hyades.ALGIEBA),
    JumpLink(JumpDifficulty.Soft, hyades.SECUNDA_HYADUM, hyades.GLENNAH),
    JumpLink(JumpDifficulty.Soft, hyades.SECUNDA_HYADUM, hyades.AIN),
    JumpLink(JumpDifficulty.Soft, hyades.SECUNDA_HYADUM, hyades.EPSILON_TAURI),
    JumpLink(JumpDifficulty.Soft, hyades.SECUNDA_HYADUM, hyades.PRIMA_HYADUM),
    JumpLink(JumpDifficulty.Soft, hyades.GENIB, hyades.ENIF),
    JumpLink(JumpDifficulty.Soft, hyades.GENIB, hyades.SCHEAT),
    JumpLink(JumpDifficulty.Hard, hyades.ALGIEBA, hyades.ALPHA_PEGASI),
    JumpLink(JumpDifficulty.Soft, hyades.ALGIEBA, hyades.GLENNAH),
    JumpLink(JumpDifficulty.Soft, hyades.ALGIEBA, hyades.MUSCIDA),
    JumpLink(JumpDifficulty.Soft, hyades.ALPHA_PEGASI, hyades.CHAMUKUY),
    JumpLink(JumpDifficulty.Moderate, hyades.ALPHA_PEGASI, hyades.AIN),
    JumpLink(JumpDifficulty.Soft, hyades.ALPHA_PEGASI, hyades.SCHEAT),
    JumpLink(JumpDifficulty.Soft, hyades.ALPHARD, hyades.ENIF),
    JumpLink(JumpDifficulty.Moderate, hyades.ALPHARD, hyades.AIN),
    JumpLink(JumpDifficulty.Moderate, hyades.CHAMUKUY, hyades.GLENNAH),
    JumpLink(JumpDifficulty.Moderate, hyades.CHAMUKUY, hyades.HYD_1192),
    JumpLink(JumpDifficulty.Soft, hyades.CHAMUKUY, hyades.EPSILON_TAURI),
    JumpLink(JumpDifficulty.Moderate, hyades.HYD_7703, hyades.GLENNAH),
    JumpLink(JumpDifficulty.Hard, hyades.HYD_7703, hyades.HYD_1192),
    JumpLink(JumpDifficulty.Hard, hyades.ENIF, hyades.AIN),
    JumpLink(JumpDifficulty.Moderate, hyades.ENIF, hyades.EPSILON_TAURI),
    JumpLink(JumpDifficulty.Hard, hyades.GLENNAH, hyades.SCHEAT),
    JumpLink(JumpDifficulty.Hard, hyades.HYD_4478, hyades.PRIMA_HYADUM),
    JumpLink(JumpDifficulty.Moderate, hyades.AIN, inner_systems.PROCYON),
    JumpLink(JumpDifficulty.Moderate, hyades.MUSCIDA, hyades.SCHEAT),
    JumpLink(JumpDifficulty.Moderate, hyades.MUSCIDA, hyades.HYD_0055),

    # ---- Polaris ----
    JumpLink(JumpDifficulty.Hard, polaris.ALFIRK, polaris.POLARIS),
    JumpLink(JumpDifficulty.Soft, polaris.ALFIRK, polaris.THUBAN),
    JumpLink(JumpDifficulty.Hard, polaris.ALFIRK, polaris.UPL_4479),
    JumpLink(JumpDifficulty.Soft, polaris.ALKAID, polaris.DUBHE),
    JumpLink(JumpDifficulty.Hard, polaris.ALKAID, polaris.SEGIN),
    JumpLink(JumpDifficulty.Soft, polaris.ALKAID, polaris.UPL_2281),
    JumpLink(JumpDifficulty.Hard, polaris.COR_CAROLI, polaris.PHERKAD),
    JumpLink(JumpDifficulty.Moderate, polaris.COR_CAROLI, polaris.THUBAN),
    JumpLink(JumpDifficulty.Moderate, polaris.DUBHE, polaris.GRUMIUM),
    JumpLink(JumpDifficulty.Soft, polaris.DUBHE, polaris.UPL_1037),
    JumpLink(JumpDifficulty.Soft, polaris.DUBHE, polaris.POLARIS),
    JumpLink(JumpDifficulty.Soft, polaris.EDASICH, polaris.ELTANIN),
    JumpLink(JumpDifficulty.Moderate, polaris.EDASICH, polaris.UPL_7741),
    JumpLink(JumpDifficulty.Moderate, polaris.ELTANIN, polaris.KOCHAB),
    JumpLink(JumpDifficulty.Soft, polaris.ELTANIN, polaris.POLARIS),
    JumpLink(JumpDifficulty.Soft, polaris.ELTANIN, polaris.RASTABAN),
    JumpLink(JumpDifficulty.Soft, polaris.GRUMIUM, polaris.KOCHAB),
    JumpLink(JumpDifficulty.Hard, polaris.UPL_7741, polaris.UPL_4479),
    JumpLink(JumpDifficulty.Soft, polaris.DUBHE, polaris.KOCHAB),
    JumpLink(JumpDifficulty.Soft, polaris.KOCHAB, polaris.THUBAN),
    JumpLink(JumpDifficulty.Moderate, polaris.NAVI, polaris.SCHEDAR),
    JumpLink(JumpDifficulty.Moderate, polaris.PHERKAD, polaris.RASTABAN),
    JumpLink(JumpDifficulty.Moderate, polaris.POLARIS, inner_systems.VEGA),
    JumpLink(JumpDifficulty.Soft, polaris.RASTABAN, polaris.SCHEDAR),
    JumpLink(JumpDifficulty.Moderate, polaris.RASTABAN, polaris.THUBAN),
    JumpLink(JumpDifficulty.Soft, polaris.SCHEDAR, polaris.SEGIN),

    # ---- Pleiades ----
    JumpLink(JumpDifficulty.Hard, pleiades.ALBIREO, pleiades.MEROPE),
    JumpLink(JumpDifficulty.Moderate, pleiades.ALBIREO, pleiades.CELAENO),
    JumpLink(JumpDifficulty.Hard, pleiades.ALBIREO, pleiades.MIRACH),
    JumpLink(JumpDifficulty.Soft, pleiades.ALBIREO, pleiades.PLX_3301),
    JumpLink(JumpDifficulty.Hard, pleiades.ALCYONE, pleiades.ALMACH),
    JumpLink(JumpDifficulty.Soft, pleiades.ALCYONE, inner_systems.ALTAIR),
    JumpLink(JumpDifficulty.Soft, pleiades.ATLAS, pleiades.MAIA),
    JumpLink(JumpDifficulty.Soft, pleiades.ALCYONE, pleiades.PLX_0010),
    JumpLink(JumpDifficulty.Hard, pleiades.ALCYONE, inner_systems.CASTOR),
    JumpLink(JumpDifficulty.Soft, pleiades.ALCYONE, pleiades.MAIA),
    JumpLink(JumpDifficulty.Soft, pleiades.ALCYONE, pleiades.MEROPE),
    JumpLink(JumpDifficulty.Moderate, pleiades.ALMACH, pleiades.PLEIONE),
    JumpLink(JumpDifficulty.Hard, pleiades.ALMACH, pleiades.SPICA),
    JumpLink(JumpDifficulty.Soft, pleiades.ASTEROPE, pleiades.MEROPE),
    JumpLink(JumpDifficulty.Soft, pleiades.ASTEROPE, pleiades.PLX_8801),
    JumpLink(JumpDifficulty.Moderate, pleiades.ASTEROPE, pleiades.PLEIONE),
    JumpLink(JumpDifficulty.Moderate, pleiades.ASTEROPE, pleiades.SPICA),
    JumpLink(JumpDifficulty.Moderate, pleiades.ATLAS, pleiades.PLX_0010),
    JumpLink(JumpDifficulty.Soft, pleiades.ATLAS, pleiades.TAYGETA),
    JumpLink(JumpDifficulty.Soft, pleiades.CELAENO, pleiades.PLX_0010),
    JumpLink(JumpDifficulty.Soft, pleiades.CELAENO, pleiades.PLX_3301),
    JumpLink(JumpDifficulty.Moderate, pleiades.CELAENO, pleiades.TAYGETA),
    JumpLink(JumpDifficulty.Soft, pleiades.PLX_0010, pleiades.PLX_6610),
    JumpLink(JumpDifficulty.Moderate, pleiades.PLX_0010, pleiades.SPICA),
    JumpLink(JumpDifficulty.Moderate, pleiades.MAIA, pleiades.MEROPE),
    JumpLink(JumpDifficulty.Soft, pleiades.MAIA, pleiades.PLX_9901),
    JumpLink(JumpDifficulty.Soft, pleiades.MAIA, pleiades.PLEIONE),
    JumpLink(JumpDifficulty.Moderate, pleiades.MIRACH, pleiades.MEROPE),
    JumpLink(JumpDifficulty.Moderate, pleiades.MIRACH, pleiades.TAYGETA),
    JumpLink(JumpDifficulty.Soft, pleiades.PLX_9901, pleiades.PLX_9902),
    JumpLink(JumpDifficulty.Soft, pleiades.PLX_9902, pleiades.ELECTRA),
]


def get_all_jump_links() -> list[JumpLink]:
    """Return the global list of JumpLinks."""
    return ALL_JUMP_LINKS
